$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-black'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Material-Sakura'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'")

hl.config({
    general = {
        gaps_in = 8,
        gaps_out = 14,
        border_size = 4,
        col = {
            active_border   = "rgba(b4637aff) rgba(d7827eff) 45deg",
            inactive_border = "rgba(286983cc) rgba(56949fcc) 45deg",
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active          = "rgba(b4637aff) rgba(d7827eff) 45deg",
            border_inactive        = "rgba(286983cc) rgba(56949fcc) 45deg",
            border_locked_active   = "rgba(b4637aff) rgba(d7827eff) 45deg",
            border_locked_inactive = "rgba(286983cc) rgba(56949fcc) 45deg",
        },
    },
    decoration = {
        rounding = 12,
        shadow = { enabled = true, ignore_window = true, offset = "6 6", range = 3, render_power = 4, color = "0xff26233a" },
        blur   = { enabled = true, size = 6, passes = 3, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
