$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-black'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Material-Sakura'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'")

hl.config({
    general = {
        gaps_in = 8,
        gaps_out = 14,
        border_size = 4,
        col = {
            active_border = { colors = {"rgba(b4637aff)", "rgba(d7827eff)"} },
            inactive_border = { colors = {"rgba(286983cc)", "rgba(56949fcc)"} },
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active = { colors = {"rgba(b4637aff)", "rgba(d7827eff)"} },
            border_inactive = { colors = {"rgba(286983cc)", "rgba(56949fcc)"} },
            border_locked_active = { colors = {"rgba(b4637aff)", "rgba(d7827eff)"} },
            border_locked_inactive = { colors = {"rgba(286983cc)", "rgba(56949fcc)"} },
        },
    },
    decoration = {
        rounding = 12,
        blur   = { enabled = true, size = 6, passes = 3, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
