$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-pink'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Rose-Pine'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 8,
        border_size = 2,
        col = {
            active_border   = "rgba(eb6f92ff) rgba(c4a7e7ff) 45deg",
            inactive_border = "rgba(31748fcc) rgba(9ccfd8cc) 45deg",
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active          = "rgba(eb6f92ff) rgba(c4a7e7ff) 45deg",
            border_inactive        = "rgba(31748fcc) rgba(9ccfd8cc) 45deg",
            border_locked_active   = "rgba(eb6f92ff) rgba(c4a7e7ff) 45deg",
            border_locked_inactive = "rgba(31748fcc) rgba(9ccfd8cc) 45deg",
        },
    },
    decoration = {
        rounding = 10,
        shadow = { enabled = false },
        blur   = { enabled = true, size = 6, passes = 3, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
