$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Gruvbox-Plus-Dark'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Gruvbox-Retro'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
os.execute("gsettings set org.gnome.desktop.interface cursor-theme 'Gruvbox-Retro'")
os.execute("gsettings set org.gnome.desktop.interface cursor-size 20")
os.execute("hyprctl setcursor Gruvbox-Retro 20")

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 8,
        border_size = 2,
        col = {
            active_border   = "rgba(90ceaaff) rgba(ecd3a0ff) 45deg",
            inactive_border = "rgba(1e8b50d9) rgba(50b050d9) 45deg",
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active          = "rgba(90ceaaff) rgba(ecd3a0ff) 45deg",
            border_inactive        = "rgba(1e8b50d9) rgba(50b050d9) 45deg",
            border_locked_active   = "rgba(90ceaaff) rgba(ecd3a0ff) 45deg",
            border_locked_inactive = "rgba(1e8b50d9) rgba(50b050d9) 45deg",
        },
    },
    decoration = {
        rounding = 3,
        shadow = { enabled = false },
        blur   = { enabled = true, size = 4, passes = 2, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
