$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-green'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Decay-Green'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 8,
        border_size = 2,
        col = {
            active_border   = "rgba(90ceaaff) rgba(ecd3a0ff) 45deg",
            inactive_border = "rgba(86aaeccc) rgba(93cee9cc) 45deg",
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active          = "rgba(90ceaaff) rgba(ecd3a0ff) 45deg",
            border_inactive        = "rgba(86aaeccc) rgba(93cee9cc) 45deg",
            border_locked_active   = "rgba(90ceaaff) rgba(ecd3a0ff) 45deg",
            border_locked_inactive = "rgba(86aaeccc) rgba(93cee9cc) 45deg",
        },
    },
    decoration = {
        rounding = 10,
        shadow = { enabled = false },
        blur   = { enabled = true, size = 5, passes = 4, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
