$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-green'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Decay-Green'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 8,
        border_size = 2,
        col = {
            active_border = { colors = {"rgba(90ceaaff)", "rgba(ecd3a0ff)"} },
            inactive_border = { colors = {"rgba(86aaeccc)", "rgba(93cee9cc)"} },
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active = { colors = {"rgba(90ceaaff)", "rgba(ecd3a0ff)"} },
            border_inactive = { colors = {"rgba(86aaeccc)", "rgba(93cee9cc)"} },
            border_locked_active = { colors = {"rgba(90ceaaff)", "rgba(ecd3a0ff)"} },
            border_locked_inactive = { colors = {"rgba(86aaeccc)", "rgba(93cee9cc)"} },
        },
    },
    decoration = {
        rounding = 10,
        shadow = { enabled = false },
        blur   = { enabled = true, size = 5, passes = 4, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
