$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-grey'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Latte'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'")

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 8,
        border_size = 2,
        col = {
            active_border   = "rgba(dc8a78ff) rgba(8839efff) 45",
            inactive_border = "rgba(7287fdcc) rgba(179299cc) 45",
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active          = "rgba(dc8a78ff) rgba(8839efff) 45",
            border_inactive        = "rgba(7287fdcc) rgba(179299cc) 45",
            border_locked_active   = "rgba(dc8a78ff) rgba(8839efff) 45",
            border_locked_inactive = "rgba(7287fdcc) rgba(179299cc) 45",
        },
    },
    decoration = {
        rounding = 10,
        shadow = { enabled = false },
        blur   = { enabled = true, size = 6, passes = 3, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
