$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-yellow'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Edge-Runner'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")

hl.config({
    general = {
        gaps_in = 8,
        gaps_out = 15,
        border_size = 4,
        col = {
            active_border   = "rgba(FADA16ff) rgba(4DBD4Fff) 45deg",
            inactive_border = "rgba(5032ACff) rgba(1F5322ff) 45deg",
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active          = "rgba(FADA16ff) rgba(4DBD4Fff) 45deg",
            border_inactive        = "rgba(5032ACff) rgba(1F5322ff) 45deg",
            border_locked_active   = "rgba(FADA16ff) rgba(4DBD4Fff) 45deg",
            border_locked_inactive = "rgba(5032ACff) rgba(1F5322ff) 45deg",
        },
    },
    decoration = {
        rounding = 0,
        shadow = { enabled = true, ignore_window = true, offset = "5 5", range = 0, render_power = 4, color = "0xffFFA6C2" },
        blur   = { enabled = true, size = 6, passes = 3, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
