$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-yellow'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Edge-Runner'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")

hl.config({
    general = {
        gaps_in = 8,
        gaps_out = 15,
        border_size = 4,
        col = {
            active_border = { colors = {"rgba(FADA16ff)", "rgba(4DBD4Fff)"} },
            inactive_border = { colors = {"rgba(5032ACff)", "rgba(1F5322ff)"} },
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active = { colors = {"rgba(FADA16ff)", "rgba(4DBD4Fff)"} },
            border_inactive = { colors = {"rgba(5032ACff)", "rgba(1F5322ff)"} },
            border_locked_active = { colors = {"rgba(FADA16ff)", "rgba(4DBD4Fff)"} },
            border_locked_inactive = { colors = {"rgba(5032ACff)", "rgba(1F5322ff)"} },
        },
    },
    decoration = {
        rounding = 0,
        blur   = { enabled = true, size = 6, passes = 3, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
