$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'BeautyLine'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Synth-Wave'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")

hl.config({
    general = {
        gaps_in = 12,
        gaps_out = 18,
        border_size = 2,
        col = {
            active_border   = "rgba(03edf9ff) rgba(72f1b8ff) 45",
            inactive_border = "rgba(495495cc) rgba(614D85cc) 45",
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active          = "rgba(03edf9ff) rgba(72f1b8ff) 45",
            border_inactive        = "rgba(495495cc) rgba(614D85cc) 45",
            border_locked_active   = "rgba(03edf9ff) rgba(72f1b8ff) 45",
            border_locked_inactive = "rgba(495495cc) rgba(614D85cc) 45",
        },
    },
    decoration = {
        rounding = 2,
        blur   = { enabled = true, size = 6, passes = 3, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
