$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Nordzy'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Nordic-Blue'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 8,
        border_size = 2,
        col = {
            active_border   = "rgba(5A9ACAB4) rgba(ECD3A0FF) 45",
            inactive_border = "rgba(1E8B50D9) rgba(32B032D9) 45",
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active          = "rgba(5A9ACAB4) rgba(ECD3A0FF) 45",
            border_inactive        = "rgba(1E8B50D9) rgba(32B032D9) 45",
            border_locked_active   = "rgba(5A9ACAB4) rgba(ECD3A0FF) 45",
            border_locked_inactive = "rgba(1E8B50D9) rgba(32B032D9) 45",
        },
    },
    decoration = {
        rounding = 7,
        shadow = { enabled = false },
        blur   = { enabled = true, size = 5, passes = 3, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
