$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-grey'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Graphite-Mono'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")

hl.config({
    general = {
        gaps_in = 8,
        gaps_out = 14,
        border_size = 3,
        col = {
            active_border = { colors = {"rgba(d9d9d9ff)", "rgba(a6a6a6ff)"} },
            inactive_border = { colors = {"rgba(404040cc)", "rgba(262626cc)"} },
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active = { colors = {"rgba(d9d9d9ff)", "rgba(a6a6a6ff)"} },
            border_inactive = { colors = {"rgba(404040cc)", "rgba(262626cc)"} },
            border_locked_active = { colors = {"rgba(d9d9d9ff)", "rgba(a6a6a6ff)"} },
            border_locked_inactive = { colors = {"rgba(404040cc)", "rgba(262626cc)"} },
        },
    },
    decoration = {
        rounding = 0,
        blur   = { enabled = true, size = 6, passes = 3, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
