$HOME/.config/hypr/themes/theme.lua|> $HOME/.config/hypr/themes/colors.lua
os.execute("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-blue'")
os.execute("gsettings set org.gnome.desktop.interface gtk-theme 'Frosted-Glass'")
os.execute("gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'")

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 10,
        border_size = 2,
        col = {
            active_border   = "rgba(2770C0ff) rgba(1E4C84ff) 45",
            inactive_border = "rgba(A44185cc) rgba(012339cc) 45",
        },
        layout = "dwindle",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active          = "rgba(2770C0ff) rgba(1E4C84ff) 45",
            border_inactive        = "rgba(A44185cc) rgba(012339cc) 45",
            border_locked_active   = "rgba(2770C0ff) rgba(1E4C84ff) 45",
            border_locked_inactive = "rgba(A44185cc) rgba(012339cc) 45",
        },
    },
    decoration = {
        rounding = 13,
        active_opacity   = 0.75,
        inactive_opacity = 0.75,
        blur   = { enabled = true, size = 4, passes = 4, new_optimizations = true, ignore_opacity = true, xray = false },
    },
})
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
